# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

$:.push File.expand_path("../lib", __FILE__)
require "soulmate_rails/version"

Gem::Specification.new do |s|
  s.name = "soulmate_rails"
  s.email = ["dhruva.sagar@gmail.com"]
  s.version = SoulmateRails::VERSION
  s.authors = ["Dhruva Sagar"]
  s.homepage = "http://github.com/dhruvasagar/soulmate_rails"
  s.summary = "Redis-backed autocompletion engine for Rails"
  s.description = "Soulmate Rails is a tool to help solve the common problem of developing a fast autocomplete feature for Rails. It uses Redis's sorted sets to build an index of partial words and corresponding top matches. Modified by Jim Zhan to add utility functions and for bug fixing."

  s.files = `git ls-files`.split("\n")
  s.test_files = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables = `git ls-files -- bin/*`.split("\n").map {|f| File.basename(f)}

  s.licenses = ["MIT"]
  s.require_paths = ["lib"]

  s.add_runtime_dependency 'redis', '>= 2.0'
  s.add_runtime_dependency 'multi_json', '>= 1.0'
  s.add_runtime_dependency 'activesupport', '>= 0'

  s.add_development_dependency 'rake', '>= 0'
  s.add_development_dependency 'rspec', '>= 0'
  s.add_development_dependency 'supermodel', '>= 0'
  s.add_development_dependency 'mock_redis', '>= 0'
end
